### PR TITLE
move SD, nw AR, ne MS, e TN

### PR DESCRIPTION
**Pull request by jacobhb175**
afaict tusculum and etsu, the only two teams affected by the E TN change, played more in the LMA region

### CODE REVIEW

**Comment by hftf** [comment]
To check, is this how you're expecting your change to look (after I fixed the missing commas)?

localhost_4000_map_


> played more in the LMA region

The region boundaries are intended tob e more about hosting, i.e. what spot should mirrors be listed under on the calendar's main page. Are Mid-Atlantic teams generally attending tournaments hosted in E Tennessee?

**Comment by jacobhb175** [comment]
I meant to also include Prentiss County, MS (INCITS #28117) in the south and the Eastern TN counties in the LMA. I know South Dakota looks rather dumb like that so, if you have any ideas, feel free to change it (or anything else in my changes, of course). As for the hosting/attending question, so far I can find 4 past tournaments in Eastern TN.
2017 Pioneer Novice:
3 Eastern TN Teams (Tusculum, ET, Carson-Newman)
3 LMA Teams (Virginia Tech A-B, W&L)
1 Deep South Team (Clemson)
2019 Pioneer Novice:
2 Eastern TN Teams (Tusculum, ET)
2 Upper South Teams (UTK A-B)
2022 Tusculum CN:
4 Upper South Teams (UTK, Belmont A-C)
4 LMA Teams (Virginia Tech, Liberty A-C)
2024 Tusculum CN:
1 Eastern TN Team (Tusculum)
1 Upper South Teams (UTK)
3 LMA Teams (Liberty A-B, SWVCC)
2 Deep South Teams (Clemson A-B)

Total:
6 Eastern TN Teams (3 Tusculum, 2 ET, 1 C-N)
7 Upper South Teams (4 UTK, 3 Belmont)
10 LMA Teams (3 VT, 5 Liberty, 1 W&L, 1 SWVCC)
3 Deep South Teams (3 Clemson)

The attendance numbers of Eastern TN tournaments tend to lean a bit more towards the Mid-Atlantic than the Upper South. That said, it is pretty close either way and I think either region would be defensible.

**Comment by hftf** [comment]
Thanks for collecting data on that case and for continued attention to the map!

I think the crux here is primarily a question of communication of goals (i.e. expand or emphasize the explanatory text on the map page). My basic thoughts are below (for hashing out further, would recommend creating new issue).

1. What are people using the map for?
    1. Primary purpose: Organize listings of tournaments on the college quizbowl calendar
    2. Portray typical size/status of college circuits at a glance
    3. Help find nearby tournaments or sets
2. In light of above, what principles should regions adhere to?
    1. Compromise/geographic simplicity
        - Follow well-known boundaries when possible (whole states)
            - Except if it would look silly (jut out), though subjective/aesthetic
        - Region membership should be easy to remember without consulting map
    2. Stability
        - Change little, but adapt to changes on-the-ground (and it has been about 5 years now so probably due)
    3. Conservative with unknowns
        - Don't represent information when not actually known

There are also other attempts to define circuits, with different goals: [1](https://quizbowlstats.com/circuits) [2](https://acf-quizbowl.com/hosting-guidelines/#regions-according-to-acf)

Non coloring of areas has indeed been a sticking point semi-frequently (see e.g. #7, [2023](https://discord.com/channels/275279348855209984/275279348855209984/1109175410387849336)). I personally don't get bothered by it, but people do react to seeing dots in areas without color.

So with respect to the current proposal,
1. I might sooner put all of ND, SD, and NE into Upper Midwest (and fix the center-of-mass) than carve out more counties.
2. I might sooner put all of MS into Deep South.
3. Noting that E TN used to be in Mid-Atlantic in 2018 (see ae8ae2a, [old image](https://discord.com/channels/275279348855209984/275279348855209984/444613501076635648)).

I'll merge (with fixes) for now but still considering what to do.

**Comment by jacobhb175** [comment]
Thanks for the explained methodology!

**Pull request closed without merging**
